[package]
name = "llrt_module_exceptions"
version = "0.4.0-beta"
edition = "2021"



[dependencies]
rquickjs = { workspace = true, features = [
  "macro",
], default-features = false }
llrt_utils = { path = "../../llrt/llrt_utils", default-features = false }
