[package]
name = "spin-app"
version = "3.1.1"
edition = "2021"

[dependencies]
spin-locked-app = { path = "../spin-locked-app" }

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }


