[package]
name = "wasmruntime-http-hello-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "components:wasmruntime-http-hello-component"

[package.metadata.component.dependencies]

[dependencies]
wasmruntime-comp-sdk = { path = "../../../crates/wasmruntime-comp-sdk", features = ["dbs"] }

wit-bindgen-rt = { workspace = true }

anyhow = { workspace = true }
http = { workspace = true }
