[package]
name = "wasmruntime-factor-dbs"
version = "3.1.1"
edition = "2021"



[dependencies]
spin-factors = { path = "../../spin/spin-factors" }
spin-resource-table = { path = "../../spin/spin-resource-table" }
spin-world = { path = "../../spin-factor/spin-world" }


wasmtime = {workspace = true}
surrealdb = {workspace = true}

anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }


async-trait = { workspace = true }


nanoid = { workspace = true }

