[package]
name = "wasmruntime-http-trigger"
version = "0.1.0"
authors = ["guyoung"]
edition = "2021"

[dependencies]
spin-app = { path = "../../spin/spin-app" }
spin-core = { path = "../../spin/spin-core" }
spin-factor-wasi = { path = "../../spin/spin-factor-wasi" }
spin-factors = { path = "../../spin/spin-factors" }
spin-http = { path = "../../spin/spin-http" }
spin-factor-outbound-http = { path = "../../spin-factor/spin-factor-outbound-http" }
spin-factor-outbound-networking = { path = "../../spin-factor/spin-factor-outbound-networking" }

wasmruntime-core = { path = "../../wasmruntime-core" }

wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }

http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }




