[package]
name = "wasmruntime-http-server"
version = "0.1.0"
authors = ["guyoung"]
edition = "2021"

[dependencies]
spin-core = { path = "../../spin/spin-core" }
spin-app = { path = "../../spin/spin-app" }
spin-http = { path = "../../spin/spin-http" }
spin-factors-executor = { path = "../../spin/spin-factors-executor" }
spin-factor-outbound-networking = { path = "../../spin-factor/spin-factor-outbound-networking" }
spin-factor-outbound-http = { path = "../../spin-factor/spin-factor-outbound-http" }

wasmruntime-core = { path = "../../wasmruntime-core" }
wasmruntime-system = { path = "../../wasmruntime-system" }
wasmruntime-http-trigger = { path = "../wasmruntime-http-trigger" }


wasmtime-wasi-http = { workspace = true }

axum = { workspace = true }
tower-http = { workspace = true, features = ["fs"] }
axum-auth = { workspace = true, default-features = false ,features = ["auth-basic"] }

anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }

http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }

[features]
default = []
dbs = ["wasmruntime-system/dbs"]
llm-infer-v1 = ["wasmruntime-system/llm-infer-v1"]
llm-infer-v2 = ["wasmruntime-system/llm-infer-v2"]
sd-infer = ["wasmruntime-system/sd-infer"]
whisper-infer = []
ncnn-infer = []
opencv = []
ffmpeg = []
