[package]
name = "spin-factor-outbound-networking"
version = "3.1.1"
edition = "2021"

[dependencies]

spin-app = { path = "../../spin/spin-app" }
spin-locked-app = { path = "../../spin/spin-locked-app" }
spin-expressions = { path = "../../spin/spin-expressions" }
spin-factors = { path = "../../spin/spin-factors" }
spin-factor-variables = { path = "../spin-factor-variables" }
spin-factor-wasi = { path = "../../spin/spin-factor-wasi" }

wasmtime-wasi = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }

futures-util = { workspace = true }

urlencoding = { workspace = true }

ipnet = { workspace = true }
http = { workspace = true }
url = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
webpki-roots = { workspace = true }





