[package]
name = "llama-infer-executor"
version = "0.1.0"
authors = ["guyoung"]
edition = "2021"

[dependencies]


llama-cpp-2 = { path = "llama-cpp-2"}
llama-cpp-sys-2 = { path = "llama-cpp-2/sys" }

anyhow = { workspace = true }
rand = { workspace = true }
encoding_rs = { workspace = true }

