[package]
name = "spin-factor-outbound-http"
version = "3.1.1"
edition = "2021"

[dependencies]
spin-factors = { path = "../../spin/spin-factors" }
spin-factor-outbound-networking = { path = "../spin-factor-outbound-networking" }

wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }

async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "net"] }

http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
ip_network = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }

