[package]
name = "spin-serde"
version = "3.1.1"
edition = "2021"

[dependencies]
wasm-pkg-common = { workspace = true }

anyhow = { workspace = true }
serde = { workspace = true }

base64 = { workspace = true }

semver = { workspace = true }


